// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: raft/raft.proto

package raft

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RaftLeaderElection_AppendEntries_FullMethodName = "/raft.RaftLeaderElection/AppendEntries"
	RaftLeaderElection_RequestVote_FullMethodName   = "/raft.RaftLeaderElection/RequestVote"
)

// RaftLeaderElectionClient is the client API for RaftLeaderElection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftLeaderElectionClient interface {
	AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
	RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error)
}

type raftLeaderElectionClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftLeaderElectionClient(cc grpc.ClientConnInterface) RaftLeaderElectionClient {
	return &raftLeaderElectionClient{cc}
}

func (c *raftLeaderElectionClient) AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendEntriesResponse)
	err := c.cc.Invoke(ctx, RaftLeaderElection_AppendEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftLeaderElectionClient) RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestVoteResponse)
	err := c.cc.Invoke(ctx, RaftLeaderElection_RequestVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftLeaderElectionServer is the server API for RaftLeaderElection service.
// All implementations must embed UnimplementedRaftLeaderElectionServer
// for forward compatibility.
type RaftLeaderElectionServer interface {
	AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error)
	RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error)
	mustEmbedUnimplementedRaftLeaderElectionServer()
}

// UnimplementedRaftLeaderElectionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftLeaderElectionServer struct{}

func (UnimplementedRaftLeaderElectionServer) AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendEntries not implemented")
}
func (UnimplementedRaftLeaderElectionServer) RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestVote not implemented")
}
func (UnimplementedRaftLeaderElectionServer) mustEmbedUnimplementedRaftLeaderElectionServer() {}
func (UnimplementedRaftLeaderElectionServer) testEmbeddedByValue()                            {}

// UnsafeRaftLeaderElectionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftLeaderElectionServer will
// result in compilation errors.
type UnsafeRaftLeaderElectionServer interface {
	mustEmbedUnimplementedRaftLeaderElectionServer()
}

func RegisterRaftLeaderElectionServer(s grpc.ServiceRegistrar, srv RaftLeaderElectionServer) {
	// If the following call panics, it indicates UnimplementedRaftLeaderElectionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaftLeaderElection_ServiceDesc, srv)
}

func _RaftLeaderElection_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftLeaderElectionServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftLeaderElection_AppendEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftLeaderElectionServer).AppendEntries(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftLeaderElection_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftLeaderElectionServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftLeaderElection_RequestVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftLeaderElectionServer).RequestVote(ctx, req.(*RequestVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftLeaderElection_ServiceDesc is the grpc.ServiceDesc for RaftLeaderElection service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftLeaderElection_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raft.RaftLeaderElection",
	HandlerType: (*RaftLeaderElectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntries",
			Handler:    _RaftLeaderElection_AppendEntries_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _RaftLeaderElection_RequestVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft/raft.proto",
}
